// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace XService.Models
{
    public partial class criminal
    {
        public int age { get; set; }
        public string name { get; set; }
        public string address { get; set; }
        public string job { get; set; }
        public string image { get; set; }
        public int p_id { get; set; }
        public string criminal_record { get; set; }
    }
}