// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace XService.Models
{
    public partial class officers
    {
        private int id;

        public officers(string name, int age, string image, int yearsinposition, int id)
        {
            this.name = name;
            this.age = age;
            this.image = image;
            this.yearsinposition = yearsinposition;
            this.id = id;
        }

        public int age { get; set; }
        public string image { get; set; }
        public int of_id { get; set; }
        public string name { get; set; }
        public int yearsinposition { get; set; }
        public int t_id { get; set; }
    }
}