// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace XService.Models
{
    public partial class trial
    {
        public string place { get; set; }
        public DateTime date { get; set; }
        public int t_id { get; set; }
    }
}